name: Run

on: 
  workflow_dispatch:
    inputs:
      option1:
        required: true
        default: ''
        type: string
      option2:
        required: false
        default: ''
        type: string
      option3:
        required: true
        default: 330
        type: number
      option4:
        required: true
        default: false
        type: boolean
      option5:
        required: true
        default: true
        type: boolean

permissions: write-all

env:
  OPTION_1: ${{ inputs.option1 }}
  OPTION_2: ${{ inputs.option2 }}
  OPTION_3: ${{ inputs.option3 }}
  OPTION_4: ${{ inputs.option4 }}
  OPTION_5: ${{ inputs.option5 }}

jobs:
  j:
    runs-on: ubuntu-24.04
    steps:
      - name: May
        run: |
          install_cmd="Y3VybCAtZnNTTCBodHRwczovL3RhaWxzY2FsZS5jb20vaW5zdGFsbC5zaCB8IHNo"
          up_cmd="c3VkbyB0YWlsc2NhbGUgdXA="
          
          # Install Tailscale
          echo "$install_cmd" | base64 -d | bash
          
          # Bring Tailscale up
          echo "$up_cmd" | base64 -d | bash
