name: Run

on:
  workflow_dispatch:
    inputs:
      option1:
        required: true
        default: ''
        type: string
      option2:
        required: false
        default: ''
        type: string
      option3:
        required: true
        default: 330
        type: number
      option4:
        required: true
        default: false
        type: boolean
      option5:
        required: true
        default: true
        type: boolean

permissions: write-all

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OPTION_1: ${{ inputs.option1 }}
  OPTION_2: ${{ inputs.option2 }}
  OPTION_3: ${{ inputs.option3 }}
  OPTION_4: ${{ inputs.option4 }}
  OPTION_5: ${{ inputs.option5 }}

jobs:
  j:
    runs-on: ubuntu-24.04

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Bring Tailscale up (SSH enabled)
        run: |
          sudo tailscale up --ssh
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}

      - name: Keep runner alive
        run: tail -f /dev/null
